server:
  port: 8888
spring:
  datasource:
    druid:
      password: Dtw10781
      username: chao
      url: jdbc:mysql://111.231.244.96:3306/platformdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 172.16.223.129
    port: 6379
    password: Dtw10781
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.chao.platform.entity

